<a href="https://colab.research.google.com/github/jamlwat/DataApplicationsBusinessJW/blob/main/rollingaveragequantity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/camdenlol/SnOasis/main/snoasisData.csv')

df["DateTime"] = pd.to_datetime(df.Date +" "+ df.Time, format = '%m/%d/%Y %I:%M:%S?%p')

df.head()

,Date,Time,Staff,Receipt number,Name,Variant,Unit,Quantity,Price (USD),Discount (USD),Subtotal (USD),Tax Info Available,Is Tax Exempt,Total tax collected (USD),Final price (USD),SKU,Barcode,Cost price,Comment,DateTime
0,2/28/2023,7:50:56?PM,SnOasis Main,1,Gift card,NaN,NaN,1,1.0,0.0,1.0,No,No,0.00,1.00,NaN,NaN,0.0,NaN,2023-02-28 19:50:56
1,2/28/2023,7:52:12?PM,SnOasis Main,2,Gift card,NaN,NaN,1,1.0,0.0,1.0,No,No,0.00,1.00,NaN,NaN,0.0,NaN,2023-02-28 19:52:12
2,2/28/2023,7:58:14?PM,SnOasis Main,3,Gift card,NaN,NaN,1,1.0,0.0,1.0,No,No,0.00,1.00,NaN,NaN,0.0,NaN,2023-02-28 19:58:14
3,2/28/2023,8:21:15?PM,SnOasis Main,4,Candy Bar,NaN,NaN,1,1.5,0.0,1.5,Yes,No,0.14,1.64,NaN,NaN,0.0,NaN,2023-02-28 20:21:15
4,2/28/2023,9:29:15?PM,SnOasis East,5,Gift card,NaN,NaN,1,1.0,0.0,1.0,No,No,0.00,1.00,NaN,NaN,0.0,NaN,2023-02-28 21:29:15

In [10]:
df["dayofyear"]=df.DateTime.dt.day_of_year

In [11]:

dfg=df.groupby("dayofyear").Quantity.sum()
dfg

dayofyear
59      13
61       7
63     918
64     993
65     792
      ...
298     24
299     94
300     19
308     45
309    157
Name: Quantity, Length: 236, dtype: int64

In [12]:
dfg.rolling(7).mean()

dayofyear
59           NaN
61           NaN
63           NaN
64           NaN
65           NaN
         ...
298    50.571429
299    53.142857
300    42.857143
308    40.285714
309    59.142857
Name: Quantity, Length: 236, dtype: float64